### ISSUE TITLE
Clear URLs not always working correctly / Counter shows still a values

### ISSUE THREAD

**Issue by Dean-Corso** [rowrawer/stream-detector#125]
Hi again rowrawer,

after using your great extension & AddOn for a longer while now I have seen some little issues with the clear URLs function. The problem is that the counter icon is not getting reset if nothing is no more in the list (all tabs / pre tabs) and the counter does show any value X on gray colored background. Entire list is empty but the counter is still showing any value. In some cases I can restart browser to fix that but sometimes not. Sometimes just a value of 1 is shown also if the list is empty. There must be any issues.

Maybe you can add a function in settings to clear all URLs when closing browser so that the counter starts with showing no value or just checkout the clear function again to make it work and reset the counter icon correctly etc. Thanks.

**Comment by rowrawer** [comment]
Hi, thanks for your report. I admit I pay absolutely no attention to the counter - I'll look into it.

**Comment by Dean-Corso** [comment]
By the way, so I can also use the disable / enable AddOn / Extension slider in the browsers to get the counter reset. In Brave I had a value of 1 left without any URL shown the list and then I did enable / disable the extension slider and the counter / value was removed and right NOW was one URL shown in your extension Previous session list which was empty before. I think there is just some little issues with that etc. Just check & fix that if possible or otherwise I'am using that detour to enable / disable the extension for a short moment. Thanks.

**Comment by rowrawer** [comment]
The counter should now be working better in v2.10.8. I've never encountered the counter counting invisible entries, so I couldn't address that, but maybe that got fixed too.

**Comment by fosam** [comment]
> The counter should now be working better in v2.10.8. I've never encountered the counter counting invisible entries, so I couldn't address that, but maybe that got fixed too.

I just tested this, `v2.10.8` and the counter is unfortunately still not accurate, i opened a tab with a stream link, the counter showed a "green" number one indicated on the icon which is correct, i closed all the tabs and opened github as the only tab, and as i'm writing this right now, i can see a "grey" number one indicated on the icon.

To fix this, (without restarting Chrome) i have to click `All tabs` then click `Clear this URL list` to clear the only link that was there, and then the icon gets cleared and no value is shown on the icon.

**Comment by fosam** [comment]
> That's how it works, if I'm understanding you correctly. The green background changes to grey and the counter shows the total amount of detections per browser session. Then it changes to green again when something gets detected again.

Possibly, but does it like show green just for a couple of seconds and then turns grey? because i've just tested now again on one tab only with an active stream, it showed green, then after some seconds it turned grey.

If i get this correctly, the green only shows for some seconds to indicate new detection then it switches back to grey which means "old" entry?

Another thing, if the counter is green and you click it, it turn grey immediately.

**Comment by fosam** [comment]
> the point is that it turns green for new detections.

I understand it better now, the green indication is like the "unread" symbol we see in the mail and similar, once read/clicked it turns grey, i don't think we have an issue now :)
Thanks

**Comment by Dean-Corso** [comment]
Hi again,

thanks for the update rowrawer. So it seems to work now to clear all URLs from the list. I also tried the new option to limit the entrys to a desired value like 5 +/- etc what also works but when I have this option enabled then it only shows the enabled value in the list like 5 but the counter is still increasing and collects URLs and all is fine so far but the problem now is to clear all URLs at once. In this case it does just clear all visible URLs from the list and then showing the next URLs which was hidden before. So this is bad when having a list of +100 URLs so then I need to press the clear URLs from list many many times you know. Just only as info for you. At the moment I have this limit option disabled so that I can clear all at once.

**Comment by rowrawer** [comment]
Thanks for your continued feedback. I feel like this behavior should remain - the button is supposed to only affect the entries that are visible. To clear the entire list, the recent entries option should first be unchecked.
